

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
  wp_data:
    driver: local

secrets:
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt